apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
        #  clusterIP: 10.100.0.1
  type: LoadBalancer
