name: CI

on: [push]


jobs:
  build:
    runs-on: self-hosted
    steps:
     - name: Check out the repo
       run: rm -rf vinay && git clone https://github.com/vinaybv77716/vinay.git
     - name: build docker image and push to ecr repo
       run: |
          sudo apt update
          sudo chown $USER /var/run/docker.sock
          ls
          pwd
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
     - name: terraform initialization 
       run: cd /home/ubuntu/actions-runner/_work/vinay/vinay/vinay/eks && terraform init 
     - name: terraform deployment
       run: cd /home/ubuntu/actions-runner/_work/vinay/vinay/vinay/eks && terraform apply  -auto-approve
     - name: Terraform apply deployment
       run: cd /home/ubuntu/actions-runner/_work/vinay/vinay/vinay/eks && kubectl apply -f deployment.yaml
     - name: Terraform apply Service
       run: cd /home/ubuntu/actions-runner/_work/vinay/vinay/vinay/eks && kubectl apply -f svc.yaml       

     
